spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:farmskin;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        hbm2ddl.auto: create-only