-- Book sample data
INSERT INTO BOOK(title, author) VALUES ('너에게 해주지 못한 말들', '권태영')
INSERT INTO BOOK(title, author) VALUES ('단순하게 배부르게', '현영서')
INSERT INTO BOOK(title, author) VALUES ('게으른 사랑', '권태영')
INSERT INTO BOOK(title, author) VALUES ('트랜드 코리아 2322', '권태영')
INSERT INTO BOOK(title, author) VALUES ('초격자 투자', '장동혁')
INSERT INTO BOOK(title, author) VALUES ('파이어족 강환국의 하면 되지 않는다! 퀀트 투자', '이예슬')
INSERT INTO BOOK(title, author) VALUES ('진심보다 밥', '이서연')
INSERT INTO BOOK(title, author) VALUES ('실패에 대하여 생각하지 마라', '위성원')
INSERT INTO BOOK(title, author) VALUES ('실리콘밸리 리더십 쉽다', '지승열')
INSERT INTO BOOK(title, author) VALUES ('데이터분석을 위한 A 프로그래밍', '지승열')
INSERT INTO BOOK(title, author) VALUES ('인공지능1-12', '장동혁')
INSERT INTO BOOK(title, author) VALUES ('-1년차 게임 개발', '위성원')
INSERT INTO BOOK(title, author) VALUES ('Skye가 알려주는 피부 채색의 비결', '권태영')
INSERT INTO BOOK(title, author) VALUES ('자연의 발전', '장지명')
INSERT INTO BOOK(title, author) VALUES ('코스모스 필 무렵', '이승열')

-- Category sample data
INSERT INTO CATEGORY(name) VALUES ('문학')
INSERT INTO CATEGORY(name) VALUES ('경제경영')
INSERT INTO CATEGORY(name) VALUES ('인문학')
INSERT INTO CATEGORY(name) VALUES ('IT')
INSERT INTO CATEGORY(name) VALUES ('과학')

-- Mapping table sample data
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(1, 1)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(2, 1)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(1, 2)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(1, 3)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(2, 4)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(2, 5)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(2, 6)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(3, 7)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(3, 8)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(4, 9)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(4, 10)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(4, 11)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(4, 12)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(4, 13)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(5, 14)
INSERT INTO CATEGORY_BOOK(categories_id, book_id) VALUES(5, 15)